engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: false
    
ratings:
  paths:
  - lib/**

exclude_paths:
  - spec/**/*
  - vendor/**/*
